# docker compose --env-file ./src/.env.development.local up -d
# docker exec -it meeting_room env
# docker logs meeting_room

version: '3.8'
services:
  db:
    # 启动容器
    container_name: meeting_room
    image: mysql
    restart: always
    ports:
      - ${mysql_server_port}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_server_password}
      MYSQL_DATABASE: ${mysql_server_database}
      # MYSQL_USER: ${mysql_server_username}
    volumes:
      - db_data_meeting_room_workshop:/var/lib/mysql
  redis:
    container_name: meeting_room_redis
    image: redis
    restart: always
    ports:
      - '${redis_server_port}:6379'
    environment:
      REDIS_PASSWORD: ${redis_server_password}
    command: ['redis-server', '--requirepass', '${redis_server_password}']
    volumes:
      - redis_data_meeting_room:/data

volumes:
  db_data_meeting_room_workshop:
  redis_data_meeting_room:
