# docker componse --env-file .env.development up -d
version: '3.8'
services:
  db:
    # 启动容器
    container_name: meeting_room
    image: mysql
    restart: always
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data_meeting_room_workshop:/var/lib/mysql
  redis:
    container_name: meeting_room_redis
    image: redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    volumes:
      - redis_data_meeting_room:/data

volumes:
  db_data_meeting_room_workshop:
  redis_data_meeting_room:
